export const ADD_ATTRIBUTE = 'ACCOUNTS:ADD_ATTRIBUTE';
export const SET_ATTRIBUTE_MODAL_VISIBLE = 'ACCOUNTS:SET_ATTRIBUTE_MODAL_VISIBLE';
export const SET_ATTRIBUTE_MODAL_LOAD = 'ACCOUNTS:SET_ATTRIBUTE_MODAL_LOAD';
export const SET_ATTRIBUTE_MODAL_ID = 'ACCOUNTS:SET_ATTRIBUTE_MODAL_ID';
